// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tri

import (
	"gorm.io/gorm"
	"interview-cases/case21_30/case21/tri/repository"
	"interview-cases/case21_30/case21/tri/repository/dao"
	"interview-cases/case21_30/case21/tri/service"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB) (*Module, error) {
	articleStaticDAO := dao.NewArticleStaticDAO(db)
	articleRepo := repository.NewArticleRepo(articleStaticDAO)
	articleSvc := service.NewArticleSvc(articleRepo)
	module := &Module{
		Svc: articleSvc,
	}
	return module, nil
}
